#!/bin/bash
make clean
make CFLAGS=-g all

valgrind --tool=memcheck --leak-check=full -s bin/test
valgrind --tool=memcheck --leak-check=full -s bin/test2
valgrind --tool=memcheck --leak-check=full -s bin/test3
