#!/bin/bash

memcheck () {
    valgrind --tool=memcheck --leak-check=full -s $1
}

if [ ! $@ ]; then
    TARGETS="lib tests"
    CHECK="bin/test2 bin/test3"
    make clean
    make CFLAGS="-g -Iinclude" $TARGETS
    for c in $CHECK; do
        memcheck $c
    done
else
    for a in $@; do
        memcheck $a
    done
fi
